### ISSUE TITLE
Error switching modes when using custom ace editor

### ISSUE THREAD

**Issue by machow** [angular-tools/ng-jsoneditor#1]
JSONEditor allows you to specify a custom ace editor. However, if you do this, then ng-jsoneditor doesn't switch between code and tree mode correctly. For example, if you start in tree mode, and try to switch to code mode, you need to select code mode twice to make the switch. It's pretty clear that code mode is being rendered by JSONEditor, but then is being switched quickly back to tree mode the first time.

I modified the jsfiddle to recreate the issue: http://jsfiddle.net/sd3at5ek/10/

I'm happy to look into it, but thought I'd see if the solution seems clear to you before looking more closely!

**Comment by angular-tools** [comment]
Hi,

I think it is because the editor is being re-created when you switch it. I will have a look soon.

> I'm happy to look into it, but thought I'd see if the solution seems clear to you before looking more closely!

In case you've figured out the problem in the directive code please let me know.. It'll help me fix it faster.

**Comment by mcblum** [comment]
@machow Hey. If you have a minute, I've checked out your fiddle and cannot, for the life of me, figure out how to pass a custom instance of Ace. We're using `"angular-ui-ace": "^0.2.3"` and for whatever reason referencing `window.ace` isn't working nor is trying to do it through Angular.

Thank you in advance for any assistance.

**Comment by mcblum** [comment]
Actually, let me clarify. Doing something like `var editor = window.ace.edit($element[0]);` is working, but we are trying to incorporate this with the json editor and I don't know how to have the actual element we care about taking account of the other version of ace.
