### ISSUE TITLE
Request Issue for the new release

### ISSUE THREAD

**Issue by orif-jr** [angular-tools/ng-jsoneditor#20]
So, guys how look your plans (month/year) for new release version to Bower? Direct usage of **ng-jsoneditor:master** as a version for bower a bit danger for our project :)
Thanks!

**Comment by elekdavid** [comment]
Hi!
That would be great for me as well...
But until then a bit safer solution if you use the last commit hash for the version
```javascript
"dependencies": {
  ...
  "ng-jsoneditor": "ea138469f157d8f2b54ec5b8dcf4b08a55b61459"
}
```

**Comment by orifn** [comment]
@elekdavid, Great! Thanks for the useful info.
