### ISSUE TITLE
Not working with angular 1.4.6

### ISSUE THREAD

**Issue by konstantinzolotarev** [angular-tools/ng-jsoneditor#3]
```html
<div name="json"
                     class="col-md-12"
                     id="json"
                     ng-model="json"
                     options="options"
                     ng-jsoneditor
                     style="height: 300px"></div>
```

```javascript
$scope.options = {
      mode: 'code',
      modes: ['code','view'], // allowed modes['code', 'form', 'text', 'tree', 'view']
      error: function (err) {
        alert(err.toString());
      }
    };
    $scope.json = {
      test: 123
    };

    $timeout(function () {
      $scope.json = {
        test: 111
      };
    }, 1000)
```

Editor always shows empty Object: `{}` 
And don't reflecting to any change

**Comment by konstantinzolotarev** [comment]
Made some tests. And found that it's not working only if I set `mode: 'code'` in options.

http://jsfiddle.net/sd3at5ek/15/

**Comment by angular-tools** [comment]
Hi,

You are right.. I will have a look today

**Comment by konstantinzolotarev** [comment]
I was able to make it work by changing timeout for set value from 100 to
10. But not sure it's a good solution. Seems that right now module set new
value and at same time 2nd timeout set it to editor value that is always
`{}`

**Comment by angular-tools** [comment]
Hi,

It should work without adjusting the timeout now. I had added the timeout at request of the jsoneditor author. The error was because it was trying to get the `editor.get()` without setting it first. I've fixed the error, so the value of timeout should not matter.

**Comment by konstantinzolotarev** [comment]
Cool. Thanks a lot. Will check in an hour.
